export const apiRoutes = {
  login : `/auth/login`,
  twoFa : `/auth/setup-2fa`,
  setup2FaVerify: `/auth/setup-2fa-verify`,
  verify2Fa : `/auth/verify-2fa`,
  refreshToken: `/auth/refresh`,
  dashboard : `/admin/dashboard`,
  recentActivities: `/admin/latest-activities`,
  user: `/auth/me`,
  logout: `/auth/logout`,
  allVulnerabilities: `/admin/all-vulnerabilities`,
  addVulnerability: (pentestId: string) => `/api/admin/pentests/${pentestId}/vulnerability`,
  uploadLogo: `/upload/company-logo`,
  signup: `/auth/signup`,
}
